version: '3.9'
services:
  backend:
    build:
      context: ./backend
    environment:
      PORT: 4000
      JWT_SECRET: change-me-in-prod
      ALLOWED_ORIGINS: http://localhost:5173,http://frontend,http://frontend:80
    ports:
      - '4000:4000'
  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_URL: http://backend:4000
    ports:
      - '5173:80'
    depends_on:
      - backend
