version: '3.9'
services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=4000
      - NODE_ENV=production
      - JWT_SECRET=change-this-in-production
      - CORS_ORIGINS=http://localhost:5173,http://frontend:80
    expose:
      - '4000'
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    environment:
      - VITE_API_BASE_URL=http://backend:4000/api
    depends_on:
      - backend
